apiVersion: v1
kind: ConfigMap
metadata:
  name: lymon-config
data:
  # Database
  MONGO_USER: "admin"
  MONGO_DB: "lymon"
  
  # Backend config
  PORT: "3000"
  isDevelopment: "true"
  # En kubernetes el backend se comunicará con otros servicios de esta forma, 
  # pero esta URL es para el frontend o correos. De momento dummy.
  APP_URL: "http://localhost:80" 
  SUPPORT_URL: "http://localhost:80/support"
  
  # Dummy values for external APIs as requested
  BREVO_API_KEY: "dummy-brevo-api-key"
  SONAR_TOKEN: "dummy-sonar-token"
---
apiVersion: v1
kind: Secret
metadata:
  name: lymon-secret
type: Opaque
stringData:
  MONGO_PASS: "secret123"
  JWT_SECRET: "my-super-secret-jwt-key"
