sonar.projectKey=lyhost-frontend
sonar.projectName=lyhost-frontend
sonar.projectVersion=1.0


sonar.sources=src
sonar.tests=src
sonar.test.inclusions=\
  src/app/presentation/features/hotel/pages/tenantProfile/tenantProfile.spec.ts,\
  src/app/presentation/features/hotel/pages/incidentReport/list/incidentReportList.spec.ts,\
  src/app/presentation/features/hotel/pages/incidentReport/edit/editIncidentReport.spec.ts,\
  src/app/presentation/features/hotel/pages/incidentReport/create/createIncidentReport.spec.ts,\
  src/app/domain/use-cases/update-incident-report.use-case.spec.ts,\
  src/app/domain/use-cases/incident/create-incident-report.use-case.spec.ts,\
  src/app/domain/use-cases/incident/get-incident-reports.use-case.spec.ts,\
  src/app/domain/use-cases/tenant/get-tenant-profile.use-case.spec.ts,\
  src/app/domain/use-cases/tenant/update-tenant-profile.use-case.spec.ts,\
  src/app/infrastructure/repositories/tenant.repository.impl.spec.ts,\
  src/app/infrastructure/repositories/incident-report.repository.impl.spec.ts

sonar.typescript.lcov.reportPaths=coverage/lymon-frontend/lcov.info,coverage/scope/lcov.info
sonar.javascript.lcov.reportPaths=coverage/lymon-frontend/lcov.info,coverage/scope/lcov.info

sonar.inclusions=\
  src/app/domain/use-cases/tenant/get-tenant-profile.use-case.ts,\
  src/app/domain/use-cases/tenant/update-tenant-profile.use-case.ts,\
  src/app/domain/use-cases/incident/get-incident-reports.use-case.ts,\
  src/app/domain/use-cases/update-incident-report.use-case.ts,\
  src/app/domain/use-cases/incident/create-incident-report.use-case.ts,\
  src/app/domain/repositories/tenant.repository.ts,\
  src/app/domain/repositories/incident-report.repository.ts,\
  src/app/infrastructure/repositories/tenant.repository.impl.ts,\
  src/app/infrastructure/repositories/incident-report.repository.impl.ts,\
  src/app/presentation/features/hotel/pages/tenantProfile/tenantProfile.ts,\
  src/app/presentation/features/hotel/pages/incidentReport/list/incidentReportList.ts,\
  src/app/presentation/features/hotel/pages/incidentReport/edit/editIncidentReport.ts,\
  src/app/presentation/features/hotel/pages/incidentReport/create/createIncidentReport.ts

sonar.exclusions=**/node_modules/**,**/dist/**,**/*.d.ts,**/seeds/**
sonar.coverage.exclusions=**/*.spec.ts,**/main.ts,**/*.module.ts,**/seeds/**
sonar.sourceEncoding=UTF-8
